reviews:
  path_filters:
    - "!walls.*"
    - "!tflow.*"
    - "!flowfield.*"
    - "!forces.*"
    - "!tdat.*"

# Change the main language setting
language: en-GB

# Also update the docstrings language setting
code_generation:
  docstrings:
    language: en-GB
